apiVersion: v1
kind: Secret
metadata:
  name: buzzword-counter-secrets
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnvironmentVariables }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-buzzword-counter
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---

apiVersion: v1
kind: Secret
metadata:
  name: buzzword-counter-postgresql-custom
type: Opaque
data:
  postgresql-host: {{ .Values.postgresql.host | b64enc | quote}}
  postgresql-name: {{ .Values.global.postgresql.postgresqlDatabase | b64enc | quote}}
  postgresql-user: {{ .Values.global.postgresql.postgresqlUsername | b64enc | quote}}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote}}
